// Heuristic importance for a file from its path, size, and a peek at its
// content head. Returns { raw, cap }: raw is an open-ended signal sum; cap is
// a hard ceiling the final 1-10 score may not exceed regardless of rank.
// collectFiles maps raw onto the 1-10 scale (10 = core architecture, 1 = pure
// noise): absolute on small repos, rank-percentile on large ones where the
// absolute scale saturates. Meditation thresholds: standard ingests 8+, deep 5+.

const MANIFESTS = new Set([
  "package.json",
  "cargo.toml",
  "pyproject.toml",
  "go.mod",
  "justfile",
  "makefile",
  "cmakelists.txt",
  "platformio.ini",
  "dockerfile",
  "build.rs",
]);

const ENTRY_STEMS = new Set(["main", "lib", "mod", "app", "cli", "server", "__init__"]);

const CODE_EXTS = new Set([
  "ts", "tsx", "js", "jsx", "mjs", "rs", "py", "go", "c", "cc", "cpp", "h", "hpp",
  "ino", "lua", "luau", "java", "kt", "swift", "rb", "php", "zig", "scad", "sh",
  "vue", "svelte", "dart",
]);
const DOC_EXTS = new Set(["md", "mdx", "rst"]);
const DATA_EXTS = new Set(["json", "yaml", "yml", "toml", "xml", "ini", "hbs", "html", "css"]);

// Penalty applied once per path (max of matching segments, not cumulative).
const NOISE_DIRS: Record<string, number> = {
  test: 20, tests: 20, __tests__: 20, spec: 20, specs: 20, mocks: 20,
  fixtures: 25, snapshots: 25, benches: 15, examples: 15,
  vendor: 30, third_party: 30, generated: 30, gen: 25,
  docs: 12, assets: 18, public: 18, static: 18, images: 20, fonts: 25,
  deprecated: 30, archive: 30, backup: 25, backups: 25, tmp: 25, temp: 25,
  logs: 20, dumps: 25, out: 20, ".yarn": 20, ".idea": 20,
};

// Any of these segments caps the final score at 3: never core architecture,
// even when a trimmed blacklist lets the file survive filtering.
const DEMOTE_DIRS = new Set([
  "vendor", "third_party", "deps", "generated", "gen", "deprecated",
  "archive", "backup", "backups", "tmp", "temp", "out", "_site",
  "storybook-static", "examples", "fixtures",
]);

const GENERATED_HEAD = /auto-?generated|generated by|do not edit/i;

export interface Scored {
  raw: number;
  cap: number;
}

export function scoreFile(path: string, loc: number, bytes = 0, head = ""): Scored {
  const segs = path.toLowerCase().split("/");
  const base = segs[segs.length - 1];
  const dot = base.lastIndexOf(".");
  const ext = dot > 0 ? base.slice(dot + 1) : "";
  const stem = dot > 0 ? base.slice(0, dot) : base;
  const dirs = segs.slice(0, -1);

  let s = 0;

  if (CODE_EXTS.has(ext)) s += 15;
  else if (DOC_EXTS.has(ext)) s += 6;
  else if (DATA_EXTS.has(ext)) s += 4;

  if (MANIFESTS.has(base)) s += 25;
  // The root README routes the repo; a nested or vendored README is a plain doc.
  else if (stem === "readme" && dirs.length === 0) s += 12;
  // Entry-point names only signal architecture when the file has substance.
  else if (ENTRY_STEMS.has(stem) && CODE_EXTS.has(ext) && loc >= 10) s += 20;
  // "index" is a weak signal: every JS directory has one, often a tiny barrel.
  else if (stem === "index" && CODE_EXTS.has(ext)) s += 10;
  else if (stem.endsWith(".config") || stem.endsWith(".conf")) s += 10;

  // Scratch / leftover files.
  if (/^(tmp|temp|old|scratch|deprecated)[._-]/.test(stem)) s -= 15;

  // Generated / derivative artifacts.
  if (ext === "map" || base.endsWith(".min.js") || stem.endsWith(".d")) s -= 25;
  // Test files by name: real code, but never core architecture.
  if (stem.endsWith(".test") || stem.endsWith(".spec") || stem.endsWith("_test")) s -= 12;

  if (dirs.includes("src")) s += 8;
  let noise = 0;
  for (const d of dirs) {
    const p = NOISE_DIRS[d];
    if (p && p > noise) noise = p;
  }
  s -= noise;

  s -= Math.min(dirs.length * 2, 10);
  s += Math.min(Math.log2(loc + 1) * 1.5, 12);

  let cap = 10;
  const capAt = (n: number) => { if (n < cap) cap = n; };

  for (const d of dirs) {
    if (DEMOTE_DIRS.has(d)) { capAt(3); break; }
  }
  // Large structured data is a dump, not architecture.
  if (DATA_EXTS.has(ext) && loc > 400) capAt(3);
  // Minified / single-line / base64 blobs.
  if (bytes > 5000 && bytes / loc > 250) capAt(1);
  if (GENERATED_HEAD.test(head)) capAt(2);
  if (ext === "map" || base.endsWith(".min.js") || base.endsWith(".min.css")) capAt(1);
  if (ext === "svg") capAt(2);
  // Runtime logs: visible, never above deep-meditation noise.
  if (ext === "log") capAt(3);
  if (stem === "changelog" && !CODE_EXTS.has(ext)) capAt(2);
  if (/^(license|licence|copying)(\.|$)/.test(base)) capAt(1);

  return { raw: s, cap };
}

// Absolute mapping for small repos: raw range is roughly -25..55, compressed to 1-10.
export function absoluteScore(raw: number): number {
  return Math.max(1, Math.min(10, Math.round((raw + 25) / 8)));
}
